baseURL = 'https://craftycode.org/'
languageCode = 'en-GB'
title = 'Crafty Code'
content = 'content/'
theme = 'craftytheme'

[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'
  [[build.cachebusters]]
    source = '(postcss|tailwind)\.config\.js'
    target = 'css'
[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'

[params]
hasCJKLanguage = "false"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = "false"

[params.social]
instagram = "crafty.code"
github = "Crafty-Code"
linkedin = "craftycode"
youtube = "craftycodeie"
buymeacoffee = "yourusername"