baseURL = 'https://craftycode.org/'
languageCode = 'en-GB'
title = 'Crafty Code'
content = 'content/'
theme = 'craftytheme'

[module]
# Remove or comment out the Ananke theme import if you no longer want to use it
# [[module.imports]]
# disable = false
# ignoreConfig = false
# ignoreImports = false
# path = 'github.com/theNewDynamic/gohugo-theme-ananke/v2'

[params]
hasCJKLanguage = "false"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = "false"

[params.social]
instagram = "crafty.code"
github = "Crafty-Code"
linkedin = "craftycode"
youtube = "craftycodeie"