baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'CraftyCode'
contentDir = "content/en/"

hasCJKLanguage = "false"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = "false"

theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]