baseURL = 'https://craftycode.org/'
languageCode = 'en-GB'
title = 'Crafty Code'
content = 'content/'

[services]
  [services.googleAnalytics]
    id = 'G-6H57MYXB4L'

hasCJKLanguage = false
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
