baseURL = 'https://craftycode.org/'
languageCode = 'en-GB'
title = 'Crafty Code'
content = 'content/'

theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]

[[params.ananke_socials]]
name = "instagram"
url = "https://www.instagram.com/crafty.code/"
[[params.ananke_socials]]
name = "github"
url = "https://github.com/Crafty-Code"
# [[params.ananke_socials]]
# name = "youtube"
# url = "https://www.youtube.com/@craftycodeie"
# [[params.ananke_socials]]
# name = "patreon"
# url = "http://www.patreon.com/craftycode"

[services]
  [services.googleAnalytics]
    id = 'G-6H57MYXB4L'

hasCJKLanguage = "false"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = "false"