  [[main]]
    name = 'Dev'
    pageRef = '/dev'
    weight = 10
  [[main]]
    name = 'Business'
    pageRef = '/business'
    weight = 20
  [[main]]
    name = 'About'
    pageRef = '/about/index'
    weight = 30