  [[main]]
    name = 'Blog'
    pageRef = '/blog'
    weight = 10
  [[main]]
    name = 'Books'
    pageRef = '/books'
    weight = 20
  [[main]]
    name = 'About'
    pageRef = '/about'
    weight = 30