  [[main]]
    name = 'Blog'
    pageRef = '/en/blog'
    weight = 10
  [[main]]
    name = 'Books'
    pageRef = '/en/books'
    weight = 20
  [[main]]
    name = 'About'
    pageRef = '/en/about/index'
    weight = 30