[[main]]
name = "Hjem"
pageRef = "/"
weight = 1

[[main]]
name = "Blog"
pageRef = "/blog/"
weight = 2

[[main]]
name = "Bøger"
pageRef = "/books/"
weight = 3

[[main]]
name = "Om"
pageRef = "/about/"
weight = 4
