[[main]]
  name = 'Blag'
  pageRef = '/blog'
  weight = 10
[[main]]
  name = 'Crafty Code'
  pageRef = '/crafty-code'
  weight = 15
[[main]]
  name = 'Leabhair'
  pageRef = '/books'
  weight = 20
[[main]]
  name = 'Fúinn'
  pageRef = '/about'
  weight = 30
