  [[main]]
    name = 'Dev'
    pageRef = '/dev'
    weight = 10
  [[main]]
    name = 'Books'
    pageRef = '/books'
    weight = 20
  [[main]]
    name = 'About'
    pageRef = '/about/index'
    weight = 30