[[main]]
name = "Início"
pageRef = "/"
weight = 1

[[main]]
name = "Blog"
pageRef = "/blog/"
weight = 2

[[main]]
name = "Livros"
pageRef = "/books/"
weight = 3

[[main]]
name = "Sobre"
pageRef = "/about/"
weight = 4
