[[main]]
  name = 'Blog'
  pageRef = '/blog'
  weight = 10
[[main]]
  name = 'Crafty Code'
  pageRef = '/crafty-code'
  weight = 15
[[main]]
  name = 'Livres'
  pageRef = '/books'
  weight = 20
[[main]]
  name = 'À propos'
  pageRef = '/about'
  weight = 30
